# Changes here will be overwritten by Copier
_commit: a093063
_src_path: https://codeberg.org/Fresh2dev/copier-f2dv-project.git
author_email: hello@f2dv.com
author_name: Donald Mellenbruch
ci_domain_name: lokalhost.net
docs_url: https://www.f2dv.com/code/r/yapx/i
funding_url: https://www.f2dv.com/funding
home_page: https://www.f2dv.com
is_minimal: false
is_python: true
license_type: MIT
package_name: yapx
project_description: Build awesome Python CLIs with ease.
project_name: yapx
python_version: '3.7'
repo_mirror: https://www.f2dv.com/code/r/yapx
repo_name: fresh2dev/yapx
repo_owner: fresh2dev
repo_url: https://www.github.com/fresh2dev/yapx

