# Changes here will be overwritten by Copier
_commit: 64c76d4
_src_path: https://codeberg.org/fresh2dev/copier-python.git
author_email: hello@fresh2.dev
author_name: donald
ci_domain_name: lokalhost.net
docs_url: https://www.Fresh2.dev/code/r/yapx/i
funding_url: https://www.Fresh2.dev/tip
package_name: yapx
project_name: yapx
python_version: '3.7'
repo_url: https://codeberg.org/Fresh2dev/yapx
