# Changes here will be overwritten by Copier
_commit: 8ea9729
_src_path: https://codeberg.org/Fresh2dev/copier-f2dv-project.git
author_email: hello@Fresh2.dev
author_name: Donald Mellenbruch
ci_domain_name: lokalhost.net
docs_url: https://www.Fresh2.dev/code/r/yapx/i
funding_url: https://www.Fresh2.dev/funding
home_page: https://www.Fresh2.dev
is_minimal: false
is_python: true
license_type: MIT
package_name: yapx
project_description: null
project_name: yapx
python_version: '3.7'
repo_mirror: https://www.Fresh2.dev/code/r/yapx
repo_name: fresh2dev/yapx
repo_owner: fresh2dev
repo_url: https://www.github.com/fresh2dev/yapx

