kind: template
load: hostbutter.jsonnet
data:
  domains: >-
    ["lokalhost.net", "fresh2.dev"]
  domainTriggers: >-
    {
      "lokalhost.net": {},
      "fresh2.dev": {
        "ref": ["refs/heads/main", "refs/tags/*"]
      }
    }
  domainClusterMap: >-
    {}
  publishRegistries: >-
    {}
  secrets: >-
    []
  secretFiles: >-
    {
      "ENV_FILE": ".env"
    }
  volumes: >-
    []
  beforeSteps: >-
    [
      {
        "name": "py-test",
        "image": "registry.lokalhost.net/fresh2dev/myke:0.0.1a20",
        "commands": [
          "myke py-requirements",
          "myke py-reports",
          "myke py-build"
        ],
        "when": {}
      }
    ]
  afterSteps: >-
    []
  finalSteps: >-
    [
      {
        "name": "py-build-package",
        "image": "registry.lokalhost.net/fresh2dev/myke:0.0.1a20",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"}
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-set-version --repository lokalhost",
          "myke py-requirements --extras build",
          "myke py-build"
        ],
        "when": {}
      },
      {
        "name": "py-publish-sandbox",
        "image": "registry.lokalhost.net/fresh2dev/myke:0.0.1a20",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-requirements --extras build",
          "myke py-publish --repository lokalhost"
        ],
        "when": {}
      },
      {
        "name": "py-publish-dev",
        "image": "registry.lokalhost.net/fresh2dev/myke:0.0.1a20",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-requirements --extras build",
          "myke py-publish --repository codeberg"
        ],
        "when": {
          "ref": ["refs/heads/dev", "refs/heads/main", "refs/tags/*"]
        }
      },
      {
        "name": "py-publish-test",
        "image": "registry.lokalhost.net/fresh2dev/myke:0.0.1a20",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-requirements --extras build",
          "myke py-publish --repository testpypi"
        ],
        "when": {
          "ref": ["refs/heads/main", "refs/tags/*"]
        }
      },
      {
        "name": "py-publish-prod",
        "image": "registry.lokalhost.net/fresh2dev/myke:0.0.1a20",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-requirements --extras build",
          "myke py-publish --repository pypi"
        ],
        "when": {
          "ref": ["refs/tags/*"]
        }
      }
    ]
  extraObjects: >-
    [
      {
        "kind": "secret",
        "name": "PYPI_CREDS",
        "get": {
          "path": "secret/data/hostbutter/global",
          "name": "PYPI_CREDS"
        }
      }
    ]
