kind: template
load: hostbutter.jsonnet
data:
  domainTriggers: >-
    {
      "lokalhost.net": {},
      "fresh2.dev": {
        "ref": ["refs/heads/main", "refs/tags/*"]
      }
    }
  domainClusterMap: >-
    {}
  dockerHubUser: ""
  secrets: >-
    []
  secretFiles: >-
    {
      "ENV_FILE": ".env"
    }
  volumes: >-
    []
  domainVars: >-
    {}
  beforeSteps: >-
    [
      {
        "name": "build-reports",
        "image": "registry.lokalhost.net/fresh2dev/myke-ci:0.0.1a14",
        "commands": [
          "myke py-requirements",
          "myke py-reports"
        ]
      }
    ]
  afterSteps: >-
    []
  finalSteps: >-
    [
      {
        "name": "py-build-package",
        "image": "registry.lokalhost.net/fresh2dev/myke-ci:0.0.1a14",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"}
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-set-version --repository lokalhost",
          "myke py-requirements -e build",
          "myke py-build"
        ],
        "when": {}
      },
      {
        "name": "py-publish-sandbox",
        "image": "registry.lokalhost.net/fresh2dev/myke-ci:0.0.1a14",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-requirements -e build",
          "myke py-publish --repository lokalhost"
        ],
        "when": {}
      },
      {
        "name": "py-publish-dev",
        "image": "registry.lokalhost.net/fresh2dev/myke-ci:0.0.1a14",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-requirements -e build",
          "myke py-publish --repository codeberg"
        ],
        "when": {
          "ref": ["refs/heads/dev", "refs/heads/main", "refs/tags/*"]
        }
      },
      {
        "name": "py-publish-test",
        "image": "registry.lokalhost.net/fresh2dev/myke-ci:0.0.1a14",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-requirements -e build",
          "myke py-publish --repository testpypi"
        ],
        "when": {
          "ref": ["refs/heads/main", "refs/tags/*"]
        }
      },
      {
        "name": "py-publish-prod",
        "image": "registry.lokalhost.net/fresh2dev/myke-ci:0.0.1a14",
        "environment": {
          "PYPI_CREDS": {"from_secret": "PYPI_CREDS"},
          "TWINE_CERT": "/etc/ssl/certs/ca-certificates.crt"
        },
        "commands": [
          "echo \"$PYPI_CREDS\" > ~/.pypirc",
          "myke py-requirements -e build",
          "myke py-publish --repository pypi"
        ],
        "when": {
          "ref": ["refs/tags/*"]
        }
      }
    ]
  extraObjects: >-
    [
      {
        "kind": "secret",
        "name": "PYPI_CREDS",
        "get": {
          "path": "secret/data/3p",
          "name": "PYPI_CREDS"
        }
      }
    ]
