#!/usr/bin/env python3
# type: ignore
# ruff: noqa
# pylint: skip-file
# flake8: noqa
import myke  # noqa

myke.require(
    pip_args=[
        "--extra-index-url",
        "https://codeberg.org/api/packages/Fresh2dev/pypi/simple",
    ],
    mykefiles="0.0.1a3.dev81",
)
from mykefiles import py_pkg  # noqa

if __name__ == "__main__":
    myke.main(__file__)
