select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    # "D",  # pydocstyle
    "F",  # pyflakes
    "UP", # pyupgrade
    # "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "ANN",# flake8-annotations
    "A",# flake8-builtins
    "COM",# flake8-commas
    "PT",# flake8-pytest-style
    "Q",# flake8-quotes
    "RET",# flake8-return
    "SIM",# flake8-simplify
    "ARG",# flake8-unused-arguments
    "PTH",# flake8-use-pathlib
    "ERA",# eradicate
    "PLW",# pylint-specific warnings
    "PLE",# pylint-specific errors
    #"PLR",# pylint-specific recommendations
    #"PLC",# pylint-specific conventions
    "RUF",# ruff-specific
    "TRY",# tryceratops
]
ignore = [
    # "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
]

# Avoid trying to fix flake8-bugbear (`B`) violations.
# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["W", "E", "COM"]
unfixable = []

respect-gitignore = true

# Same as Black.
line-length = 88

target-version = "py37"

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[per-file-ignores]
"__init__.py" = ["E402", "F401"]
