site_name: "yapx"
site_description: "yapx documentation"
site_url: "https://www.Fresh2.dev/code/r/yapx/i/docs"
repo_url: "https://codeberg.org/Fresh2dev/yapx"
repo_name: "Gitea"
edit_uri_template: "src/branch/main/{path}"
docs_dir: "../docs"
site_dir: "../public/docs"

theme:
  name: readthedocs

## https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
# nav:
#   - Home: index.md
#   ...

watch:
  - ../src

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          options:
            show_bases: true
            show_source: false
            members_order: 'source'  # 'alphabetical'
            show_submodules: true
            docstring_style: google
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            show_if_no_docstring: false
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            show_root_members_full_path: true
            show_object_full_path: false
            show_category_heading: false
